#!/bin/bash

rm -f output.txt ; touch output.txt ; clear ; tail -f output.txt

#./resources/filler_vm -f resources/maps/map00 -p1 resources/players/plagache.filler -p2 resources/players/carli.filler > game_res


#read -e -p "player1 should be ?
#" PLYR1
#read -e -p "player2 should be ?
#" PLYR2
#read -e -p "map to play on is ?
#" map
#
#./filler_vm -f "$map" -p1 "$PLYR1" -p2 "$PLYR2" > game_res
