#!/bin/bash

read -e -p "Your player?
" PLYR;
read -e -p "The map ?
" MAP;
read -e -p "The opponent?
" OPPO;
read -e -p "Number of games?
" GAMES;

for ((x = 1; x <= $GAMES; x++))
do
	echo "GAME No:$x";
	./filler_vm -q -p1 $PLYR -p2 $OPPO -f $MAP;
	res=$(cat filler.trace | grep "won" | cut -d" " -f1);
	if [[ $res == $PLYR ]];
	then
		score_p1=$((score_p1 + 1));
	fi;
	./filler_vm -q -p2 $PLYR -p1 $OPPO -f $MAP;
	res=$(cat filler.trace | grep "won" | cut -d" " -f1);
	if [[ $res == $PLYR ]];
	then
		score_p2=$((score_p2 + 1));
	fi;
	echo "score as P1 is $score_p1/$x";
	echo "score as P2 is $score_p2/$x";
done
